module(load="imfile" PollingInterval="1")
module(load="mmjsonparse")

input(type="imfile"
      File="/var/ossec/logs/archives/archives.json"
      Tag="wazuh-archive:"
      Severity="info"
      Facility="local0"
      readMode="0"
      PersistStateInterval="20"
      reopenOnTruncate="on"
      deleteStateOnFileDelete="on")

template(name="agentTaggedForward" type="string"
         string="<134>%timestamp:::date-rfc3164% %$!agent!name% %$!full_log%\n")

if $programname == 'wazuh-archive' then {
    action(type="mmjsonparse" cookie="")
    action(type="omfwd"
           target="__FORWARD_TARGET__"
           port="__FORWARD_PORT__"
           protocol="udp"
           template="agentTaggedForward")
    stop
}
